apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-volume
  namespace: orba-workshop
  labels:
    app: nginx-with-volume
spec:
  selector:
    matchLabels:
      app: nginx-with-volume
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-with-volume
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: my-claim


