kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-claim
  namespace: orba-workshop
  labels:
    app: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1M
