apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: orba-workshop
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: nginx
  type: ClusterIP
