apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nginx-statefulset
  name: nginx-statefulset
  namespace: orba-workshop
spec:
  serviceName: "nginx-statefulset"
  replicas: 1
  selector:
    matchLabels:
      app: nginx-statefulset
  template:
    metadata:
      labels:
        app: nginx-statefulset
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 3
              periodSeconds: 3
          envFrom:
            - configMapRef:
                name: my-config
      restartPolicy: Always
